package com.cb.chat.model.completion.chat;

import lombok.Data;

/**
 * A chat completion generated by GPT-3.5
 * chatgpt返回结果实体类
 */
@Data
public class ChatCompletionChoice {

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    /**
     * The {@link ChatMessageRole} message which was generated.
     */
    ChatMessage message;

    /**
     * The reason why GPT-3 stopped generating, for example "length".
     */
    String finishReason;
}
